spring:
  application:
    name: admin-server-ms

server:
  port: 32768

logger:
  name: admin-server-log
  path: D://Java - MS - Dev End - End//00.Log//${logger.name}.log
logging:
  config: classpath:logback.xml